### ISSUE TITLE
Giveaway command

### ISSUE THREAD

**Issue by andrewcgraves** [CactusBot/CactusBot#250] opened 2017-03-07 03:43 UTC
Selecting a viewer out of a collection of viewers that typed in `!join` within a given time limit

**Comment by Alkali-Metal** [comment] 2017-03-07 03:57
Duplicate of [#112](https://github.com/CactusDev/CactusBot/issues/112)...

**Comment by 2Cubed** [comment] 2017-03-07 04:22
Yep - duplicate of #112. (We can continue discussion there!)

**Closed as completed by 2Cubed** 2017-03-07 04:22 UTC
Labels: duplicate
